<a href="https://colab.research.google.com/github/lorenzovaresio/AI_Medicine/blob/main/notebooks/Introduction%20to%20Python/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pandas

[pandas](https://pandas.pydata.org/docs/index.html#module-pandas) is an open-source, BSD-licensed library that provides **high-performance**, **easy-to-use** data structures and tools for **data analysis** in Python.

This is a short introduction to **pandas**, intended for new users.  
For more advanced examples, refer to the official [Cookbook](https://pandas.pydata.org/pandas-docs/stable/user_guide/cookbook.html#cookbook).

To use pandas, we first need to **import** the module:

In [1]:
# Importing pandas
import pandas as pd

The module is typically imported as `pd` by convention.

## pandas DataFrame

pandas provides two primary classes for working with data:

1. **Series** – a one-dimensional labeled array (like a column)
2. **DataFrame** – a two-dimensional table with rows and columns (like an Excel spreadsheet)

We can create a `DataFrame` by passing a **list of dictionaries**,  
where each dictionary represents a row, and the keys are column names.

In [ ]:
# Example: List of Dictionaries as Data
data = [{'ID': '001', 'Age': 68, 'Sex':'M', 'CT':2.543}, {'Age': 56, 'ID': '002', 'Sex': 'F', 'CT':2.34}, {'Age': 56, 'ID': '003', 'Sex': 'F', 'CT':2.41}]
print (type(data))
print (type(data[0]))

<class 'list'>
<class 'dict'>

In [ ]:
# Creating a DataFrame
df = pd.DataFrame(data)
print (df)

    ID  Age Sex     CT
0  001   68   M  2.543
1  002   56   F  2.340
2  003   56   F  2.410

This creates a `DataFrame` where each row comes from one dictionary in the list.  
The column names are automatically inferred from the keys.

### Column data types

The columns of a DataFrame can have **different data types**.

By default:
- Numbers are stored as `int` or `float`
- Strings are stored as `object` dtype (which can hold any type, including strings)

You can convert object columns to actual string type (`str`) if needed (df['ColumnName'] = df['ColumnName'].astype('string') )

In [ ]:
# Checking Data Types of Each Column
df.dtypes

ID      object
Age      int64
Sex     object
CT     float64
dtype: object

This will display the data type (`dtype`) of each column in the DataFrame.

# Viewing data

To quickly inspect a DataFrame, you can use the `.head()` and `.tail()` methods.

- `df.head(n)` shows the **first `n` rows**
- `df.tail(n)` shows the **last `n` rows**

See the [Essential basic functionality section](https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#basics) for more details.

In [ ]:
# View the First 2 Rows
df.head(2)

    ID  Age Sex     CT
0  001   68   M  2.543
1  002   56   F  2.340

In [ ]:
# View the Last Row
df.tail(1)

    ID  Age Sex    CT
2  003   56   F  2.41

### Display column names

You can access the column names of a DataFrame using the `.columns` attribute.

In [ ]:
# View Column Names
df.columns

Index(['ID', 'Age', 'Sex', 'CT'], dtype='object')

# DataFrame shape

The `.shape` attribute returns a **tuple** representing the dimensions of the DataFrame:  
`(number of rows, number of columns)`

In [ ]:
# View DataFrame Shape
df.shape

(3, 4)

### Selecting a Column

You can access a single column of a DataFrame using **dot notation** (`df.ColumnName`) or **bracket notation** (`df['ColumnName']`).

This returns a `Series` object — a one-dimensional array-like structure.

In [ ]:
# Example: Access the 'CT' Column
CT_dataset = df.CT
print (CT_dataset)
print (type(CT_dataset))

0    2.543
1    2.340
2    2.410
Name: CT, dtype: float64
<class 'pandas.core.series.Series'>

The result is a pandas `Series` containing all the values from the `'CT'` column.

# Summary Statistics

The `.describe()` method provides a quick statistical summary of the **numerical columns** in your DataFrame.

It includes:
- Count
- Mean
- Standard deviation
- Min and max
- Quartiles (25%, 50%, 75%)

In [ ]:
# Example: Descriptive Statistics
df.describe()

             Age        CT
count   3.000000  3.000000
mean   60.000000  2.431000
std     6.928203  0.103116
min    56.000000  2.340000
25%    56.000000  2.375000
50%    56.000000  2.410000
75%    62.000000  2.476500
max    68.000000  2.543000

## Selection

You can select specific data from a DataFrame using **labels** or **conditions**.

For detailed reference, see:
- [Indexing and Selecting Data](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing)
- [Advanced Indexing](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html#advanced)

### Selecting a single column

Passing a **column label** (string) in brackets selects that column and returns a `Series`.

This is equivalent to using dot notation (`df.Age`), but bracket notation is preferred when column names have spaces or special characters.

In [ ]:
df["Age"]

0    68
1    56
2    56
Name: Age, dtype: int64

In [ ]:
# Example: Select 'Age' Column
df.Age

0    68
1    56
2    56
Name: Age, dtype: int64

### Selecting rows by slice

For a DataFrame, using slicing syntax like `start:stop` selects **rows by position**,  
where `stop` is **excluded** (just like with Python lists).

In [ ]:
# Example: Select First Two Rows
df[0:2]

    ID  Age Sex     CT
0  001   68   M  2.543
1  002   56   F  2.340

# Selection by Position with iloc

You can use `.iloc[]` to select rows and columns **by integer position**.  
For more details, see the [Selection by Position documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-integer).

In [ ]:
# Example: Select Row at Position 2
df.iloc[2]

ID      003
Age      56
Sex       F
CT     2.41
Name: 2, dtype: object

This returns the **third row** (index starts at 0) as a Series.

# Integer slicing with iloc

Integer slicing with `.iloc[]` behaves similarly to standard Python and NumPy slicing.  
You can use row and column indices to extract specific parts of the DataFrame.

In [ ]:
# Example: Select Row 2, Columns 0 and 1
df.iloc[2, 0:2]

ID     003
Age     56
Name: 2, dtype: object

This selects the element(s) at row index `2` and column indices `0` and `1` (column `2` is excluded).

# Selecting specific elements with lists of positions

You can also pass **lists of integer positions** to `.iloc[]` to select **multiple rows and columns**.

In [ ]:
# Example: Select Rows 0 and 1, Columns 0 and 2
df.iloc[[0,1], [0,2]]

    ID Sex
0  001   M
1  002   F

This selects a subset of the DataFrame:  
- Rows at positions 0 and 1  
- Columns at positions 0 and 2

For slicing rows explicitly:

In [ ]:
df.iloc[0:2,:]

    ID  Age Sex     CT
0  001   68   M  2.543
1  002   56   F  2.340

# Slicing rows explicitly

You can use `:` to slice rows explicitly and select **all columns** by including `:` in the column position.

In [ ]:
df.iloc[:, 0:2]

    ID  Age
0  001   68
1  002   56
2  003   56

This selects **all rows** and **columns 0 and 1**.

### Accessing a specific value

To access a **single value** in the DataFrame by its **row and column position**, use:

In [ ]:
df.iloc[0,0]

'001'

## Missing Data

In pandas, **missing data** is typically represented using `np.nan` (Not a Number),  
which comes from NumPy.

Missing values are **automatically excluded** from most computations (like `mean`, `sum`, etc.).

For more details, see the [Missing Data section](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#missing-data).

# Dropping Missing Data

The method `DataFrame.dropna()` removes any **rows** that contain at least one missing value (`NaN`).

This is useful when you want to work only with **complete cases** (no missing data).

In [ ]:
import numpy as np
import pandas as pd

data1 = [{'ID': '001', 'Age': np.nan, 'Sex':'M', 'CT':2.543}, {'Age': 56, 'ID': '002', 'Sex': 'F', 'CT':2.34}, {'Age': 56, 'ID': '003', 'Sex': 'F', 'CT':2.41}]
print (type(data1)) # List of dictionaries
print (type(data1[0])) # Each element is a dictionary

df1 = pd.DataFrame(data1)
print (df1)

<class 'list'>
<class 'dict'>
    ID   Age Sex     CT
0  001   NaN   M  2.543
1  002  56.0   F  2.340
2  003  56.0   F  2.410

This creates a DataFrame with one missing value (`NaN`) in the `'Age'` column of the first row.

In [ ]:
# Drop Rows with Any Missing Values (creates a new DataFrame)
df2 = df1.dropna(how="any")
print (df2) # Only rows without NaN are kept
print (df1) # The original DataFrame remains unchanged

    ID   Age Sex    CT
1  002  56.0   F  2.34
2  003  56.0   F  2.41
    ID   Age Sex     CT
0  001   NaN   M  2.543
1  002  56.0   F  2.340
2  003  56.0   F  2.410

In [ ]:
# Drop Rows with Any Missing Values (modifies the original DataFrame)
df1.dropna(how="any", inplace=True)
print(df1) # Now df1 has been updated: rows with NaN are removed

    ID   Age Sex    CT
1  002  56.0   F  2.34
2  003  56.0   F  2.41

- `how="any"`: drop rows if **any column** has a missing value  
- `inplace=True`: perform the operation **in place** without returning a new DataFrame

## Stats

By default, pandas **excludes missing data** (`NaN`) from statistical operations.

You can compute common statistics such as **mean**, **sum**, **min**, **max**, etc.

In [ ]:
# Example: Mean of selected columns
df[['Age', 'CT']].mean()

Age    60.000
CT      2.431
dtype: float64

This computes the mean only for the `'Age'` and `'CT'` columns.

# pandas exercises

Use the following `DataFrame` to solve the exercises below:

```python
import numpy as np
import pandas as pd

data = [
    {'ID': '001', 'Age': 68, 'Sex': 'M', 'CT': 2.543},
    {'ID': '002', 'Age': 56, 'Sex': 'F', 'CT': 2.340},
    {'ID': '003', 'Age': 56, 'Sex': 'F', 'CT': 2.410},
    {'ID': '004', 'Age': np.nan, 'Sex': 'M', 'CT': 2.500},
    {'ID': '005', 'Age': 60, 'Sex': 'F', 'CT': np.nan}
]

df = pd.DataFrame(data)

In [5]:
# Exercise 1

# Display:
#	•	The first 2 rows of the DataFrame

#	•	The shape of the DataFrame
import numpy as np
import pandas as pd

data = [
    {'ID': '001', 'Age': 68, 'Sex': 'M', 'CT': 2.543},
    {'ID': '002', 'Age': 56, 'Sex': 'F', 'CT': 2.340},
    {'ID': '003', 'Age': 56, 'Sex': 'F', 'CT': 2.410},
    {'ID': '004', 'Age': np.nan, 'Sex': 'M', 'CT': 2.500},
    {'ID': '005', 'Age': 60, 'Sex': 'F', 'CT': np.nan}
]

df = pd.DataFrame(data)

#	•	The first 2 rows of the DataFrame
df.iloc[0:2, :]

    ID   Age Sex     CT
0  001  68.0   M  2.543
1  002  56.0   F  2.340

In [6]:
#	•	The column names
df.columns

Index(['ID', 'Age', 'Sex', 'CT'], dtype='object')

In [7]:
#	•	The shape of the DataFrame
df.shape

(5, 4)

In [14]:
# Exercise 2

# Access the "CT" column and calculate its mean.
df_CT = df.CT
df_CT
print(df_CT.mean())

2.44825

In [15]:
# Exercise 3

# Drop all rows that contain missing values and store the result in a new DataFrame.
# Then print the shape of the new DataFrame.

df_not_nan = df.dropna(how="any")
print(df_not_nan.shape)

(3, 4)

In [25]:
# Exercise 4

# Select and display only the "Age" and "CT" columns, but only for rows where Sex == 'F'.

df_females = df[df['Sex'] == 'F']
print(df_females.shape)
df_result = df_females[['Age', 'CT']]
df_result

(3, 4)

    Age    CT
1  56.0  2.34
2  56.0  2.41
4  60.0   NaN

In [30]:
# Exercise 5

# Using .iloc, extract:
#	•	The third row of the DataFrame
#	•	The value in the second row, third column (by position)


df_4 = df.iloc[3, :]
df_4
value = df.iloc[1, 2]
print(value)

F

In [33]:
# Exercise 6

# Replace missing values in the "Age" column with the mean of the non-missing ages.

df_5 = df.dropna(how = "any")
mean_age = df_5["Age"].mean()
print(mean_age)

df['Age'] = df['Age'].fillna(mean_age)
print(df)

60.0
    ID   Age Sex     CT
0  001  68.0   M  2.543
1  002  56.0   F  2.340
2  003  56.0   F  2.410
3  004  60.0   M  2.500
4  005  60.0   F    NaN